test_that("utils works", {
  # a <- get_ipab_region(folder = tempdir(), sheet = 1, region = "M")
  # expect_equal(ncol(a), 2)
  # b <- get_ipab_region(folder = tempdir(), sheet = 1, region = "I")
  # expect_equal(ncol(b), 2)
  # expect_error(get_ciiu(folder = 1))
  # expect_error(get_ciiu(version = "messi"))
  ech_2018 <- age_groups(data = ech::toy_ech_2018, cut = c(0, 4, 11, 17, 24))
  expect_true("age_groups" %in% names(ech_2018))
  ech_2018 <- age_groups(data = ech::toy_ech_2018, cut = c(2, 4, 11, 17, 24))
  expect_true("age_groups" %in% names(ech_2018))
  toy_ech_2018 <- organize_ht11(data = ech::toy_ech_2018, year = 2014)
  expect_equal(ncol(toy_ech_2018), 581)
})
