# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

archive_metadata <- function(path) {
    .Call('_ech_archive_metadata', PACKAGE = 'ech', path)
}

archive_filters <- function() {
    .Call('_ech_archive_filters', PACKAGE = 'ech')
}

archive_formats <- function() {
    .Call('_ech_archive_formats', PACKAGE = 'ech')
}

libarchive_version_ <- function() {
    .Call('_ech_libarchive_version_', PACKAGE = 'ech')
}

archive_extract_ <- function(archive_filename, filenames, sz = 16384L) {
    invisible(.Call('_ech_archive_extract_', PACKAGE = 'ech', archive_filename, filenames, sz))
}

read_connection <- function(archive_filename, filename, mode, format, filters, sz = 16384L) {
    .Call('_ech_read_connection', PACKAGE = 'ech', archive_filename, filename, mode, format, filters, sz)
}

